modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/QbDesu/Proxies/issues"
license="Unlicense"

[[mods]]
modId="proxies"
version="${file.jarVersion}"
displayName="Proxies"
updateJSONURL="https://gist.githubusercontent.com/QbDesu/134ab0df3a1580f6df6dc55383d58eae/raw/proxies_update.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/proxies"
logoFile="proxies.png"
credits="Thanks to the Forge Team, the Forge Discord Channel, and the MMD Discord Channel."

authors="Qb"
description='''
A mod that provides passive blocks that provide access to target blocks' inventories.
'''

[[dependencies.proxies]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.proxies]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4]"
    ordering="NONE"
    side="BOTH"
